# 放在 repo 根目錄下的 environment.yml
channels:
  - conda-forge
  - defaults

dependencies:
  # 使用 conda 安裝核心套件／避免二進位衝突
  - python=3.6
  - numpy=1.16.4
  - scipy=1.2.0
  - h5py=2.9.0
  - matplotlib=2.2.3
  - tensorflow-gpu=1.14.0
  - tensorflow-estimator=1.14.0
  - protobuf=3.9.1
  - grpcio=1.23.0
  - keras=2.2.4
  - pip

  # 只用 pip 安裝 GitHub 套件與純 Python libraries
  - pip:
      # PoPS 核心程式
      - git+https://github.com/Jason033/PoPS.git@master
      - gym=0.10.9
      - Box2D==2.3.2
      # 以下為純 Python、或 conda-forge 上較難取得的套件
      - absl-py==0.7.1
      - astor==0.8.0
      - attrs==19.1.0
      - bleach==3.1.0
      - chardet==3.0.4
      - configparser==3.7.4
      - decorator==4.4.0
      - defusedxml==0.6.0
      - entrypoints==0.3
      - future==0.17.1
      - gast==0.2.2
      - google-pasta==0.1.7
      - ipykernel==4.10.0
      - ipython==5.8.0
      - ipywidgets==7.4.2
      - Jinja2==2.10.1
      - jsonschema==3.0.1
      - jupyter==1.0.0
      - Keras-Applications==1.0.8
      - Keras-Preprocessing==1.1.0
      - notebook==5.7.8
      - pyglet==1.3.2
      - tqdm==4.30.0
      - widgetsnbextension==3.4.2
