name: mybinder-env
channels: 
   - conda-forge
   - defaults
dependencies:
   # core Python and conda packages
   - python=3.6
   - pip
   - jupyter=1.0.0
   - notebook=5.7.8
   - ipykernel=4.10.0
   - ipython=5.8.0
   - numpy=1.16.4
   - scipy=1.2.0
   - matplotlib=2.2.3
   - pandas
   - opencv
   - tensorflow-estimator
   - tensorboard
   - grpcio=1.23.0
   # install Box2D from conda-forge rather than pip (avoids need for SWIG)
   - box2d-py
   # include common Jupyter extensions
   - ipywidgets=7.4.2
   - widgetsnbextension=3.4.2
   - cmake  
   # remaining packages via pip
   - pip:
     - tensorflow_probability==0.7.0
     - tensorflow==1.15.5
     - absl-py==0.7.1
     - asn1crypto==0.24.0
     - astor==0.8.0
     - attrs==19.1.0
     - backports-abc==0.5
     - backports.functools-lru-cache==1.5
     - backports.shutil-get-terminal-size==1.0.0
     - backports.weakref==1.0.post1
     - binarytree==4.0.0
     - bleach==3.1.0
     # Box2D==2.3.2  # replaced by box2d-py above
     - certifi==2018.11.29
     - chardet==3.0.4
     - configparser==3.7.4
     - cycler==0.10.0
     - decorator==4.4.0
     - defusedxml==0.6.0
     - entrypoints==0.3
     - enum34==1.1.6
     - funcsigs==1.0.2
     - future==0.17.1
     - gast==0.2.2
     - google-pasta==0.1.7
     - gym==0.10.9
     - h5py==2.9.0
     - idna==2.8
     - ipython-genutils==0.2.0
     - Jinja2==2.10.1
     - jsonschema==3.0.1
     - jupyter-client==5.2.4
     - jupyter-console==5.2.0
     - jupyter-core==4.4.0
     - Keras-Applications==1.0.8
     - Keras-Preprocessing==1.1.0
     - keyring==10.6.0
     - keyrings.alt==3.0
     - kiwisolver==1.0.1
     - Markdown==3.1.1
     - MarkupSafe==1.1.1
     - mistune==0.8.4
     - mock==3.0.5
     - nbconvert==5.4.1
     - nbformat==4.4.0
     - pandocfilters==1.4.2
     - pathlib2==2.3.3
     - pbr==5.1.2
     - pexpect==4.7.0
     - pickleshare==0.7.5
     - prometheus-client==0.6.0
     - prompt-toolkit==1.0.16
     - protobuf==3.9.1
     - ptyprocess==0.6.0
     - pyglet==1.3.2
     - Pygments==2.3.1
     - pyparsing==2.3.1
     - pyrsistent==0.14.11
     - python-dateutil==2.8.0
     - pytz==2018.9
     - pyzmq==18.0.1
     - qtconsole==4.4.3
     - requests==2.21.0
     - scandir==1.10.0
     - SecretStorage==2.3.1
     - Send2Trash==1.5.0
     - simplegeneric==0.8.1
     - singledispatch==3.4.0.3
     - six==1.12.0
     - subprocess32==3.5.3
     - termcolor==1.1.0
     - terminado==0.8.2
     - testpath==0.4.2
     - tornado==5.1.1
     - tqdm==4.30.0
     - traitlets==4.3.2
     - wcwidth==0.1.7
     - webencodings==0.5.1
     - Werkzeug==0.15.5
     - wrapt==1.11.2
